name: Release

on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_call:
  workflow_dispatch:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - macos-latest
          - windows-latest
          - ubuntu-latest
        include:
          # - os: macos-latest
          #   platform: darwin
          - os: windows-latest
            platform: win32
          - os: ubuntu-latest
            platform: linux

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: Set Yarn Version to Berry
        run: yarn set version berry

      - name: Install dependencies
        run: yarn install

      - name: Install extra dependencies for Linux
        if: matrix.platform == 'linux'
        run: sudo apt-get install -y rpm

      - name: Build
        run: yarn build

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: |
            release/*/*.exe
            release/*/*.appx
            release/*/*.AppImage
            release/*/*.deb
            release/*/*.rpm
            release/*/*.dmg
            release/*/*.zip
          retention-days: 15

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: release

      - name: Display Artifacts
        run: ls -l release

      - name: Extract Tag
        id: extract_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          title: Release ${{ steps.extract_tag.outputs.tag }}
          files: |
            release/**/*
