name: Release

on:
  push:
    branches:
      - master
  workflow_call:
  workflow_dispatch:


jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            platform: darwin
          - os: windows-latest
            platform: win32
          - os: ubuntu-latest
            platform: linux

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPOSITORY }}
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: |
            release/*/*.exe
            release/*/*.appx
            release/*/*.AppImage
            release/*/*.deb
            release/*/*.rpm
            release/*/*.dmg
            release/*/*.zip
          retention-days: 15
